--- # PROD.main.yml
name: Azure Function deploy
on: {push: {branches: [main]} }
jobs:
  build:
    name: Build/Stage
    permissions: {contents: read}
    runs-on: windows-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Install Node
        id: node
        uses: actions/setup-node@v4
        with: {node-version: 24}
      - name: Install Dependencies
        id: ci
        run: npm ci --loglevel=error --fund=false
      - name: Build Function App
        id: build
        run: npm run deploy
      - name: Stage to Azure Functions
        id: stage
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .
  deploy:
    name: Deploy
    needs: build
    permissions:
      id-token: write
      contents: read
    runs-on: windows-latest
    steps:
      - name: Download Staged Function App
        id: download
        uses: actions/download-artifact@v4
        with: {name: node-app}
      - name: Authenticate to Azure
        id: auth
        uses: Azure/login@v2
        with:
          client-id: ${{secrets.AZUREAPPSERVICE_CLIENTID_3034D1B136904402BF0455EAC32E3E58}}
          tenant-id: ${{secrets.AZUREAPPSERVICE_TENANTID_DB8A0D0B724C45D09A05D2B620297020}}
          subscription-id: ${{secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_9E0B741A5C8640DB87DCC64CCE0370DF}}
      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: jo
          slot-name: Production
          package: .

...
